'use strict';

const fs = require('fs');
const path = require('path');

const START = '<!-- agentkit:start -->';
const END = '<!-- agentkit:end -->';

// Rulebook files an agent tool actually reads. sync injects the managed block
// into every one that exists; if none exist it seeds CLAUDE.md (the default).
const DEFAULT_RULEBOOKS = ['CLAUDE.md', 'AGENTS.md', 'GEMINI.md', '.cursor/rules/agentkit.md'];
const SEED_RULEBOOK = 'CLAUDE.md';

function renderBlock(assets) {
  const skills = assets.filter((a) => a.kind === 'skill').sort((a, b) => a.name.localeCompare(b.name));
  const agents = assets.filter((a) => a.kind === 'agent').sort((a, b) => a.name.localeCompare(b.name));
  const commands = assets.filter((a) => a.kind === 'command').sort((a, b) => a.name.localeCompare(b.name));

  const lines = [
    START,
    '## Agentic layer (AgentKit — auto-generated, do not edit between the markers)',
    '',
    'Enforcement + reusable playbooks come from `@arches/agentkit` (config `agentkit.config.json`, wired in `.claude/settings.json`). Guardrails intercept agent tool calls automatically; their block messages state the compliant next step. Regenerated by `npx agentkit sync` — edit the source in the AgentKit repo, never here.',
  ];

  if (skills.length) {
    lines.push('', '**Skills — invoke the matching one when its situation applies:**', '', '| Skill | Use when |', '|---|---|');
    for (const s of skills) lines.push(`| \`${s.name}\` | ${clean(s.description)} |`);
  }
  if (commands.length) {
    lines.push('', '**Commands:**');
    for (const c of commands) lines.push(`- \`/${c.name}\` — ${clean(c.description)}`);
  }
  if (agents.length) {
    lines.push('', '**Subagents — dispatch when relevant:**');
    for (const a of agents) lines.push(`- \`${a.name}\` — ${clean(a.description)}`);
  }
  lines.push('', END);
  return lines.join('\n');
}

function clean(desc) {
  return String(desc || '').replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim() || '(see the asset for details)';
}

// Replace an existing fenced block, else append one. Content outside the fence
// is never touched.
function upsertBlock(content, block) {
  const src = content || '';
  const s = src.indexOf(START);
  const e = src.indexOf(END);
  if (s !== -1 && e !== -1 && e > s) {
    const before = src.slice(0, s);
    const after = src.slice(e + END.length);
    return before + block + after;
  }
  const base = src.replace(/\s*$/, '');
  return (base ? base + '\n\n' : '') + block + '\n';
}

// Remove the fenced block (leave all other content). Returns null if unchanged.
function removeBlock(content) {
  const src = content || '';
  const s = src.indexOf(START);
  const e = src.indexOf(END);
  if (s === -1 || e === -1 || e < s) return null;
  const out = (src.slice(0, s) + src.slice(e + END.length)).replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '');
  return out;
}

// Strip the block from every rulebook that carries it (used by uninstall).
function unwireRulebooks(repoRoot) {
  const removed = [];
  for (const rel of DEFAULT_RULEBOOKS) {
    const abs = path.join(repoRoot, rel);
    let cur;
    try { cur = fs.readFileSync(abs, 'utf8'); } catch { continue; }
    const next = removeBlock(cur);
    if (next !== null && next !== cur) { fs.writeFileSync(abs, next); removed.push(rel); }
  }
  return removed;
}

function targetRulebooks(repoRoot, config) {
  const cfg = config && config.rulebooks;
  if (cfg === false) return [];
  const list = Array.isArray(cfg) && cfg.length ? cfg : DEFAULT_RULEBOOKS;
  const existing = list.filter((rel) => {
    try { return fs.statSync(path.join(repoRoot, rel)).isFile(); } catch { return false; }
  });
  return existing;
}

// Inject/update the block in every existing target rulebook; if none exist and
// injection isn't opted out, seed SEED_RULEBOOK with just the block.
function wireRulebooks(repoRoot, config, assets) {
  if (config && config.rulebooks === false) return { written: [], seeded: null };
  const block = renderBlock(assets);
  const targets = targetRulebooks(repoRoot, config);
  const written = [];
  if (targets.length) {
    for (const rel of targets) {
      const abs = path.join(repoRoot, rel);
      const cur = fs.readFileSync(abs, 'utf8');
      const next = upsertBlock(cur, block);
      if (next !== cur) { fs.writeFileSync(abs, next); written.push(rel); }
    }
    return { written, seeded: null };
  }
  const seedAbs = path.join(repoRoot, SEED_RULEBOOK);
  fs.mkdirSync(path.dirname(seedAbs), { recursive: true });
  fs.writeFileSync(seedAbs, `# ${path.basename(repoRoot)}\n\n` + block + '\n');
  return { written: [SEED_RULEBOOK], seeded: SEED_RULEBOOK };
}

// doctor: does every existing target already contain the current block?
function rulebookStatus(repoRoot, config, assets) {
  if (config && config.rulebooks === false) return { ok: true, stale: [], missing: false };
  const block = renderBlock(assets);
  const targets = targetRulebooks(repoRoot, config);
  if (!targets.length) return { ok: false, stale: [], missing: true };
  const stale = targets.filter((rel) => {
    const cur = fs.readFileSync(path.join(repoRoot, rel), 'utf8');
    return upsertBlock(cur, block) !== cur;
  });
  return { ok: stale.length === 0, stale, missing: false };
}

module.exports = { START, END, DEFAULT_RULEBOOKS, SEED_RULEBOOK, renderBlock, upsertBlock, removeBlock, wireRulebooks, unwireRulebooks, rulebookStatus, targetRulebooks };
